import json
import io
import urllib.error

import pytest

from yt_transcript_apify import client as c
from yt_transcript_apify.cli import main as cli_main

ROW_OK = {
    "videoId": "arj7oStGLkU",
    "url": "https://www.youtube.com/watch?v=arj7oStGLkU",
    "input": "arj7oStGLkU",
    "status": "success",
    "title": "Inside the Mind of a Master Procrastinator",
    "channelName": "TED",
    "language": "en",
    "isAutoGenerated": False,
    "text": "So in college, I was a government major.",
    "segments": [{"start": 1.2, "duration": 2.0, "end": 3.2, "text": "So in college,"}],
    "srt": "1\n00:00:01,200 --> 00:00:03,200\nSo in college,\n",
}
ROW_NONE = {"input": "x", "status": "no_captions", "message": "The video has no captions."}


class FakeResp:
    def __init__(self, data):
        self._b = json.dumps(data).encode()

    def read(self):
        return self._b

    def __enter__(self):
        return self

    def __exit__(self, *a):
        return False


@pytest.fixture
def capture(monkeypatch):
    seen = {}

    def fake_urlopen(req, timeout=None):
        seen["url"] = req.full_url
        seen["headers"] = dict(req.header_items())
        seen["body"] = json.loads(req.data.decode())
        return FakeResp(seen.get("reply", [ROW_OK]))

    monkeypatch.setattr(c.urllib.request, "urlopen", fake_urlopen)
    monkeypatch.setenv("APIFY_TOKEN", "test-token")
    return seen


def test_video_url_and_id():
    assert c.video_url("arj7oStGLkU") == "https://www.youtube.com/watch?v=arj7oStGLkU"
    assert c.video_url("https://youtu.be/arj7oStGLkU") == "https://youtu.be/arj7oStGLkU"
    assert c.video_id("https://www.youtube.com/shorts/arj7oStGLkU") == "arj7oStGLkU"
    with pytest.raises(ValueError):
        c.video_url("not a video")


def test_fetch_sends_expected_request(capture):
    t = c.ApifyTranscriptClient().fetch("arj7oStGLkU", languages=["es"])
    assert capture["url"].startswith(c.API_BASE + "/acts/nokia2k~youtube-transcript-scraper/run-sync-get-dataset-items")
    assert capture["headers"]["Authorization"] == "Bearer test-token"
    assert capture["body"]["videoUrls"] == ["https://www.youtube.com/watch?v=arj7oStGLkU"]
    assert capture["body"]["languages"] == ["es"]
    assert t.title.startswith("Inside")
    assert t.segments == [{"text": "So in college,", "start": 1.2, "duration": 2.0}]


def test_get_transcript_dropin(capture):
    assert c.get_transcript("arj7oStGLkU") == [{"text": "So in college,", "start": 1.2, "duration": 2.0}]
    assert capture["body"]["languages"] == ["en"]


def test_no_captions_raises(capture):
    capture["reply"] = [ROW_NONE]
    with pytest.raises(c.TranscriptError) as e:
        c.ApifyTranscriptClient().fetch("arj7oStGLkU")
    assert e.value.status == "no_captions"


def test_missing_token(monkeypatch):
    monkeypatch.delenv("APIFY_TOKEN", raising=False)
    monkeypatch.delenv("APIFY_API_TOKEN", raising=False)
    with pytest.raises(c.MissingTokenError):
        c.ApifyTranscriptClient().fetch("arj7oStGLkU")


def test_http_error(monkeypatch):
    def boom(req, timeout=None):
        raise urllib.error.HTTPError(req.full_url, 401, "Unauthorized", {}, io.BytesIO(b'{"error":"bad token"}'))

    monkeypatch.setattr(c.urllib.request, "urlopen", boom)
    monkeypatch.setenv("APIFY_TOKEN", "x")
    with pytest.raises(c.TranscriptError, match="401"):
        c.ApifyTranscriptClient().fetch("arj7oStGLkU")


def test_cli_srt(capture, capsys):
    assert cli_main(["arj7oStGLkU", "--format", "srt"]) == 0
    assert capture["body"]["outputFormats"] == ["srt"]
    assert "00:00:01,200" in capsys.readouterr().out


def test_cli_reports_failures(capture, capsys):
    capture["reply"] = [ROW_OK, ROW_NONE]
    assert cli_main(["arj7oStGLkU", "dQw4w9WgXcQ"]) == 1
    out = capsys.readouterr()
    assert "government major" in out.out and "no captions" in out.err


def test_mcp_tools(capture):
    from yt_transcript_apify import mcp_server as m

    out = m.get_youtube_transcript("arj7oStGLkU", output="srt")
    assert capture["body"]["outputFormats"] == ["srt"] and "Title: Inside" in out
    capture["reply"] = [ROW_OK, ROW_NONE]
    many = m.get_youtube_transcripts(["arj7oStGLkU", "dQw4w9WgXcQ"])
    assert "government major" in many and "No transcript" in many
