"""Small client for the nokia2k YouTube Transcript Scraper on Apify.

YouTube blocks most requests that come from cloud servers (AWS, GCP, Azure,
Vercel, Render ...). Libraries that call YouTube directly then fail with
``RequestBlocked`` / ``IpBlocked`` / HTTP 429. This client sends the work to an
Apify Actor that handles proxies and retries, and returns plain Python data.

Only the standard library is used.
"""

from __future__ import annotations

import json
import os
import re
import urllib.error
import urllib.request
from dataclasses import dataclass, field
from typing import Any, Iterable

ACTOR_ID = "nokia2k~youtube-transcript-scraper"
API_BASE = "https://api.apify.com/v2"
DEFAULT_TIMEOUT = 300

_ID_RE = re.compile(r"^[A-Za-z0-9_-]{11}$")
_URL_ID_RE = re.compile(r"(?:v=|youtu\.be/|/shorts/|/embed/|/live/|/v/)([A-Za-z0-9_-]{11})")


class TranscriptError(Exception):
    """Raised when the Apify call fails or the video has no usable transcript."""

    def __init__(self, message: str, status: str | None = None, row: dict | None = None):
        super().__init__(message)
        self.status = status
        self.row = row or {}


class MissingTokenError(TranscriptError):
    """Raised when no Apify API token is available."""


def video_url(video: str) -> str:
    """Accept an 11-character video ID or any YouTube link and return a link."""
    video = video.strip()
    if _ID_RE.match(video):
        return f"https://www.youtube.com/watch?v={video}"
    if "youtube.com" in video or "youtu.be" in video:
        return video
    raise ValueError(f"Not a YouTube video ID or link: {video!r}")


def video_id(video: str) -> str | None:
    """Return the 11-character ID of a link or ID, or ``None`` when not found."""
    video = video.strip()
    if _ID_RE.match(video):
        return video
    m = _URL_ID_RE.search(video)
    return m.group(1) if m else None


@dataclass
class Transcript:
    """One video's result. ``segments`` holds ``{"text", "start", "duration"}`` dicts."""

    video_id: str | None
    title: str | None
    language: str | None
    is_generated: bool | None
    text: str
    segments: list[dict] = field(default_factory=list)
    srt: str | None = None
    vtt: str | None = None
    raw: dict = field(default_factory=dict)

    @classmethod
    def from_row(cls, row: dict) -> "Transcript":
        segments = [
            {"text": s.get("text", ""), "start": s.get("start", 0.0), "duration": s.get("duration", 0.0)}
            for s in (row.get("segments") or [])
        ]
        return cls(
            video_id=row.get("videoId"),
            title=row.get("title"),
            language=row.get("language"),
            is_generated=row.get("isAutoGenerated"),
            text=row.get("text") or " ".join(s["text"] for s in segments),
            segments=segments,
            srt=row.get("srt"),
            vtt=row.get("vtt"),
            raw=row,
        )


class ApifyTranscriptClient:
    """Fetch YouTube transcripts through Apify.

    ``token`` defaults to the ``APIFY_TOKEN`` environment variable. Get a free
    token at https://console.apify.com/settings/integrations (the free plan
    includes $5 of credit every month).
    """

    def __init__(self, token: str | None = None, timeout: int = DEFAULT_TIMEOUT, actor_id: str = ACTOR_ID):
        self.token = token or os.environ.get("APIFY_TOKEN") or os.environ.get("APIFY_API_TOKEN")
        self.timeout = timeout
        self.actor_id = actor_id

    # -- low level -----------------------------------------------------------------
    def run(self, actor_input: dict) -> list[dict]:
        """Run the Actor synchronously and return its dataset rows."""
        if not self.token:
            raise MissingTokenError(
                "No Apify token. Set APIFY_TOKEN or pass token=... "
                "(free token: https://console.apify.com/settings/integrations)"
            )
        url = f"{API_BASE}/acts/{self.actor_id}/run-sync-get-dataset-items?timeout={int(self.timeout)}"
        body = json.dumps(actor_input).encode("utf-8")
        req = urllib.request.Request(
            url,
            data=body,
            method="POST",
            headers={
                "Content-Type": "application/json",
                "Authorization": f"Bearer {self.token}",
                "User-Agent": "youtube-transcript-apify/0.1",
            },
        )
        try:
            with urllib.request.urlopen(req, timeout=self.timeout + 30) as resp:
                data = json.loads(resp.read().decode("utf-8") or "[]")
        except urllib.error.HTTPError as e:
            detail = e.read().decode("utf-8", "replace")[:500]
            raise TranscriptError(f"Apify returned HTTP {e.code}: {detail}") from None
        except urllib.error.URLError as e:
            raise TranscriptError(f"Could not reach Apify: {e.reason}") from None
        if not isinstance(data, list):
            raise TranscriptError(f"Unexpected answer from Apify: {str(data)[:300]}")
        return data

    # -- high level ----------------------------------------------------------------
    def fetch_many(
        self,
        videos: Iterable[str],
        languages: Iterable[str] | None = None,
        formats: Iterable[str] = ("segments", "text"),
        translate_to: str | None = None,
    ) -> list[dict]:
        """Return one raw row per video, in the order given. Failed videos keep their
        ``status`` and ``message`` (they are not charged)."""
        urls = [video_url(v) for v in videos]
        if not urls:
            return []
        actor_input: dict[str, Any] = {
            "videoUrls": urls,
            "outputFormats": list(formats),
            "languages": list(languages) if languages else ["auto"],
            "fallbackToAnyLanguage": True,
        }
        if translate_to:
            actor_input["translateTo"] = translate_to
        return self.run(actor_input)

    def fetch(
        self,
        video: str,
        languages: Iterable[str] | None = None,
        formats: Iterable[str] = ("segments", "text"),
        translate_to: str | None = None,
    ) -> Transcript:
        """Fetch one video. Raises ``TranscriptError`` when it has no transcript."""
        rows = self.fetch_many([video], languages=languages, formats=formats, translate_to=translate_to)
        if not rows:
            raise TranscriptError("Apify returned no rows")
        row = rows[0]
        if row.get("status") != "success":
            raise TranscriptError(
                row.get("message") or f"No transcript ({row.get('status')})", status=row.get("status"), row=row
            )
        return Transcript.from_row(row)


def get_transcript(
    video_id: str, languages: Iterable[str] = ("en",), token: str | None = None
) -> list[dict]:
    """Drop-in for the classic ``YouTubeTranscriptApi.get_transcript`` call.

    Returns ``[{"text": ..., "start": ..., "duration": ...}, ...]``. The
    language list works as a preference; when none of them exists, the
    video's original language is returned.
    """
    return ApifyTranscriptClient(token=token).fetch(video_id, languages=languages).segments
