"""LangChain document loader: YouTube transcripts as `Document`s, from cloud servers too.

    pip install "youtube-transcript-apify[langchain]"

    from yt_transcript_apify.langchain import YouTubeTranscriptApifyLoader
    docs = YouTubeTranscriptApifyLoader(["https://youtu.be/arj7oStGLkU"]).load()
"""

from __future__ import annotations

from typing import Iterator, Optional, Sequence

try:
    from langchain_core.document_loaders import BaseLoader
    from langchain_core.documents import Document
except ImportError as exc:  # pragma: no cover - exercised only without the extra
    raise ImportError(
        'The LangChain loader needs langchain-core: pip install "youtube-transcript-apify[langchain]"'
    ) from exc

from .client import ApifyTranscriptClient

_META_FIELDS = ("videoId", "url", "title", "channelName", "language", "isAutoGenerated", "durationSeconds")


class YouTubeTranscriptApifyLoader(BaseLoader):
    """Load the transcripts of YouTube videos or Shorts, one `Document` per video.

    Videos without a transcript are skipped (or raise, with ``skip_missing=False``).
    Metadata carries the video ID, URL, title, channel, language and duration.
    """

    def __init__(
        self,
        videos: Sequence[str],
        languages: Optional[Sequence[str]] = None,
        translate_to: Optional[str] = None,
        skip_missing: bool = True,
        client: Optional[ApifyTranscriptClient] = None,
    ) -> None:
        self.videos = list(videos)
        self.languages = list(languages) if languages else None
        self.translate_to = translate_to
        self.skip_missing = skip_missing
        self.client = client or ApifyTranscriptClient()

    def lazy_load(self) -> Iterator[Document]:
        rows = self.client.fetch_many(
            self.videos, languages=self.languages, formats=["text"], translate_to=self.translate_to
        )
        for row in rows:
            if row.get("status") != "success":
                if self.skip_missing:
                    continue
                raise ValueError(f"{row.get('input')}: {row.get('message') or row.get('status')}")
            meta = {key: row.get(key) for key in _META_FIELDS if row.get(key) is not None}
            meta["source"] = row.get("url")
            yield Document(page_content=row.get("text") or "", metadata=meta)
